name: .NET Core CI

on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-dotnet:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

  restore:
    runs-on: windows-latest
    steps:
      - name: Restore NuGet packages
        run: |
          cd 'D:\Vs Projects\ContinuousIntegrationWithCoreMvc'
          dotnet restore
    needs: [setup-dotnet]

  build:
    runs-on: windows-latest
    steps:
      - name: Build
        run: |
          cd 'D:\Vs Projects\ContinuousIntegrationWithCoreMvc'
          dotnet build -c Debug
    needs: [restore]

  test:
    runs-on: windows-latest
    steps:
      - name: Run unit tests
        run: |
          cd 'D:\Vs Projects\ContinuousIntegrationWithCoreMvc'
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverageThreshold=80
    needs: [build]

  deploy:
    runs-on: windows-latest
    steps:
      - name: Deploy to GitHub
        run: |
          git config --global user.name 'Musayyab Ali'
          git config --global user.email 'meharmusayyab713@gmail.com'
          git add .
          git commit -m "Automated deployment"
          git push origin main
    needs: [test]
